### ISSUE TITLE
Plugin renames all artboards as "__~

### ISSUE THREAD

**Issue by KITSTABAntonioBertossi** [KevinvBre/Sketch-Rename-Artboards#2]
Hi there, just installed your plugin on latest version of Sketch (53.2) and I can't seem able to make it work. All artboards get renames as `__` and I'm not sure I'm doing something wrong or the plugin is no longer compatible with Sketch. Be good to hear back from you!

![image](https://user-images.githubusercontent.com/49231742/55714034-d1958580-59e9-11e9-8bf8-7f28175cba3f.png)

**Comment by Nivekvb** [comment]
Hey, yes well thats the plan. They are named "__" because that keeps them selectable in Sketch and easy to delete on export for not having any 'designs' in them. I use them for titles pages and small documentation.

**Comment by KITSTABAntonioBertossi** [comment]
Thanks @KevinvBre, I'd done a test with some random rectangles into the page but at that point it didn't seem to work. I now figured out. 👏 Works like a charm! Thanks very much and thank you also for putting together this plugin, very useful.
